# Generated by Django 4.2.1 on 2023-05-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AirportName', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartureDateTime', models.DateTimeField()),
                ('ArrivalDateTime', models.DateTimeField()),
                ('DepartureAirportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DepartureAirportID', to='serviceAirline.airports')),
                ('DestinationAirportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DestinationAirportID', to='serviceAirline.airports')),
            ],
        ),
        migrations.AddField(
            model_name='airports',
            name='CityID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceAirline.cities'),
        ),
    ]
