# Generated by Django 4.2.1 on 2023-05-13 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AirportName', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentReference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartureDateTime', models.DateTimeField()),
                ('ArrivalDateTime', models.DateTimeField()),
                ('DepartureAirportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DepartureAirportID', to='serviceAirline.airports')),
                ('DestinationAirportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DestinationAirportID', to='serviceAirline.airports')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReservationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Row', models.CharField(max_length=2)),
                ('SeatNumber', models.IntegerField()),
                ('SeatStatus', models.CharField(choices=[('A', 'Availible'), ('R', 'Reserved')], max_length=10)),
                ('ClassID', models.CharField(max_length=20)),
                ('SeatPrice', models.IntegerField()),
                ('FlightID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceAirline.flights')),
                ('ReservationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceAirline.reservations')),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=4)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('PassportNumber', models.IntegerField()),
                ('BookingID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceAirline.bookings')),
                ('Seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceAirline.seats')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='FlightID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceAirline.flights'),
        ),
        migrations.AddField(
            model_name='airports',
            name='CityID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceAirline.cities'),
        ),
        migrations.AddConstraint(
            model_name='seats',
            constraint=models.UniqueConstraint(fields=('FlightID', 'Row', 'SeatNumber'), name='SeatPK'),
        ),
    ]
