# Generated by Django 4.2.1 on 2023-05-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAirline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='SeatPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
