# Generated by Django 4.2.1 on 2023-05-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAirline', '0003_alter_seats_classid'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='AvailibleSeats',
            field=models.IntegerField(null=True),
        ),
    ]
