# Generated by Django 4.2.1 on 2023-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAirline', '0004_flights_availibleseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='Currency',
            field=models.CharField(default='GBP', max_length=3),
            preserve_default=False,
        ),
    ]
