# Generated by Django 4.2.1 on 2023-05-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAirline', '0005_seats_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='DurationMins',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
