# Generated by Django 4.2.1 on 2023-05-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAirline', '0008_flights_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='Airline',
            field=models.CharField(default='Virgin', max_length=20),
            preserve_default=False,
        ),
    ]
